[develop < T0034-GA] Add Field to models
memgraph/gqlalchemy pull request #122
Opened 2022-04-04 16:19 UTC by katarinasupe

### Description

I added the possibility of importing Field from `gqlalchemy.models`. Since `Node` and `Relationship` are in `gqlalchemy.models`, it makes sense to import `Field` from there too.

### Pull request type

- [x] Other

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

2022-04-05 11:11 UTC, BorisTasevski requested changes
We need to discuss this further

2022-04-08 11:23 UTC, katarinasupe commented
We will further discuss for the next release.

2022-05-09 13:02 UTC, g-despot commented
What needs to be discussed here? @katarinasupe 
I think this approach is much better than importing it from pydantic.

2022-05-18 15:08 UTC, brunos252 approved these changes

2022-05-18 19:49 UTC, BorisTasevski approved these changes

2022-05-20 07:36 UTC, g-despot approved these changes

2022-05-20 07:59 UTC, merged