[develop < T0066-GA] Add foreach to query builder
memgraph/gqlalchemy pull request #135
Opened 2022-04-19 15:01 UTC by brunos252

### Description

grammar for foreach is:
foreach : FOREACH '(' variable IN expression '|' updateClause+ ')' ;
- where updateClause can be SET, REMOVE, CREATE, MERGE, DELETE and FOREACH

Problem is that there is a ')' after updateClause so it can't be chained together.
Currently, the idea is to have a simple ForeachPartialQuery, where update_clause is passed as a string from another_query_builder.construct_query()

### Pull request type

- [x] Feature

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

2022-05-04 14:12 UTC, Josipmrden requested changes

2022-05-26 14:10 UTC, katarinasupe requested changes

2022-05-26 14:10 UTC, katarinasupe commented on gqlalchemy/query_builder.py
> +            update_clauses: One or more cypher update clauses:
```suggestion
            update_clauses: One or more Cypher update clauses:
```

2022-06-08 09:08 UTC, BorisTasevski requested changes

2022-06-08 09:08 UTC, BorisTasevski commented on gqlalchemy/query_builder.py
> +        return "" if self._variable is None else self._variable
We have discussed this `None` -> "" conversion. We should  keep this in constructor. If it can't be `None`, remove this conversion

2022-06-08 09:08 UTC, BorisTasevski commented on gqlalchemy/query_builder.py
> +        return "" if self._expression is None else self._expression
We have discussed this `None` -> "" conversion. We should  keep this in constructor. If it can't be `None`, remove this conversion

2022-06-08 09:08 UTC, BorisTasevski commented on gqlalchemy/query_builder.py
> +        return "" if self._update_clauses is None else self._update_clauses
We have discussed this `None` -> "" conversion. We should  keep this in constructor. If it can't be `None`, remove this conversion

2022-06-10 05:10 UTC, g-despot approved these changes

2022-06-13 03:31 UTC, BorisTasevski approved these changes

2022-06-13 08:06 UTC, Josipmrden approved these changes

2022-06-13 08:55 UTC, katarinasupe approved these changes

2022-06-13 09:15 UTC, merged