[T0071-GA < DFS] add dfs and tests
memgraph/gqlalchemy pull request #144
Opened 2022-05-04 15:23 UTC by brunos252

### Description

This is a copy-paste of #142, replacing `*bfs` with `*` and making DepthFirstSearch instead of BreadthFirstSearch.

### Pull request type

- [x] Feature

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

2022-05-06 14:36 UTC, katarinasupe requested changes
Similar comments apply to this PR as in BFS.

2022-05-06 14:36 UTC, katarinasupe commented on tests/memgraph/test_query_builder.py
> +def test_dfs_bounds():
Add tests for `lower_bound` and all combinations.

2022-05-12 10:01 UTC, katarinasupe approved these changes

2022-05-13 11:18 UTC, Josipmrden reviewed
Minor comments

2022-05-13 11:18 UTC, Josipmrden commented on gqlalchemy/memgraph.py
> +        self.condition = condition
Explain the arguments in pydocs

2022-05-13 11:18 UTC, Josipmrden commented on gqlalchemy/memgraph.py
> +
algo_str = f"{algo_str} {filter_lambda}"

2022-05-13 11:18 UTC, Josipmrden commented on gqlalchemy/memgraph.py
> +
Same for above in bounds

2022-05-13 11:18 UTC, Josipmrden commented on gqlalchemy/memgraph.py
> +
Good one, just keep doing ternary operators when double choiced! :+1:

2022-05-17 10:41 UTC, BorisTasevski requested changes

2022-05-17 10:41 UTC, BorisTasevski commented on gqlalchemy/memgraph.py
> +        lower = str(self.lower_bound) if self.lower_bound is not None else ""
Could we move this logic to ctor?

2022-05-17 10:41 UTC, BorisTasevski commented on gqlalchemy/memgraph.py
> +        upper = str(self.upper_bound) if self.upper_bound is not None else ""
Could we move this logic to ctor?

2022-05-17 12:44 UTC, BorisTasevski approved these changes

2022-05-17 13:15 UTC, merged