[develop < T0093] Add query module arguments as tuples
memgraph/gqlalchemy pull request #155
Opened 2022-05-26 10:08 UTC by Josipmrden

### Description

Please briefly explain the changes you made here.

### Pull request type

Please delete options that are not relevant.

- [ ] Bugfix
- [ X ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring with functional or API changes
- [ ] Refactoring without functional or API changes
- [ ] Build or packaging related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete section if this PR doesn't resolve any issues. 

Closes (link to issue)

### Checklist:

- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ X ] My changes generate no new warnings
- [ X ] I have added tests that prove my fix is effective or that my feature works
- [ X ] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

2022-05-26 13:08 UTC, BorisTasevski approved these changes

2022-05-27 06:51 UTC, katarinasupe requested changes

2022-05-27 06:51 UTC, katarinasupe commented on gqlalchemy/query_builder.py
> +            return ", ".join([to_cypher_value(x) for x in arguments])
`x` is not descriptive, maybe use `arg` or `argument`.

2022-05-27 06:51 UTC, katarinasupe commented on gqlalchemy/query_builder.py
> +    def _parse_query_arguments(self, arguments: Optional[Union[str, Tuple[Union[str, int, float]]]]) -> str:
Similar methods were called `to_cypher_<>`, e.g., `to_cypher_qm_arguments()`, and located in [utilities](https://github.com/memgraph/gqlalchemy/blob/develop/gqlalchemy/utilities.py#L40). Let me know what you think, this is just a suggestion.

2022-05-27 06:51 UTC, katarinasupe commented on tests/docs/test_query_builder.py
> +def test_call_procedure_arguments_tuple():
Maybe mix up `int` and `str` in tuple just to check it all.

2022-06-09 10:26 UTC, brunos252 commented
I reviewed this PR, but won't approve so that it can't be merged withoud addressing @katarinasupe 's changes.

2022-06-10 05:17 UTC, g-despot approved these changes

2022-06-10 05:18 UTC, g-despot commented
If there is no concrete reason for updating it, please refrain from pushing changes to the Poetry lock file. @Josipmrden

2022-06-10 13:07 UTC, brunos252 approved these changes

2022-06-13 09:07 UTC, katarinasupe approved these changes

2022-06-13 09:35 UTC, merged