T0067 ga/sync push stream query modules
memgraph/gqlalchemy pull request #158
Opened 2022-05-26 14:04 UTC by niko4299

### Description

Please briefly explain the changes you made here.

### Pull request type

Please delete options that are not relevant.

- [ ] Bugfix
- [X ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring with functional or API changes
- [ ] Refactoring without functional or API changes
- [ ] Build or packaging related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

Delete section if this PR doesn't resolve any issues. 

Closes (link to issue)

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ X ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

2022-05-26 14:25 UTC, Josipmrden commented on gqlalchemy/memgraph.py
> +        query = f"CALL mg.create_module_file('kafka.py','{file_text}') YIELD *"
Put this in separate private method with argument of file_path

2022-06-08 11:17 UTC, katarinasupe requested changes

2022-06-08 11:17 UTC, katarinasupe commented on gqlalchemy/memgraph.py
> +        return self._add_query_module(file_path=file_path, module_name=module_name)
Add return types

2022-06-09 10:04 UTC, brunos252 requested changes
I see you merged some other PR's into your branch. Now when I go to Files changed I can see all those changes that you didn't make, making it a bit harder to review. 
I think since you branched from develop you should only track and merge changes in develop.
If there is a good reason for merging or you think differently, let me know, also regarding any of my comments, as I am also learning here.

2022-06-09 10:04 UTC, brunos252 commented on tests/memgraph/test_query_modules.py
> +
Name of this file might be a bit confusing, there is a `test_query_modules.py` within `tests/graph_algorithms/`, and this tests the addition of query modules, so these tests could either be in `test_memgraph.py`, or be named more specifically, something like `test_add_query_modules.py`

2022-06-13 06:42 UTC, Josipmrden commented on gqlalchemy/exceptions.py
> +class GQLAlchemyResultQueryTypeError(TypeError):
Will fix

2022-06-13 06:44 UTC, Josipmrden commented on gqlalchemy/exceptions.py
> +def gqlalchemy_error_handler(func):
Makes sense

2022-06-13 06:44 UTC, Josipmrden commented on gqlalchemy/memgraph.py
> -
Will do

2022-06-13 06:45 UTC, Josipmrden commented on gqlalchemy/memgraph.py
> +        """Function for adding query module.
Yes definitely makes sense, will update that the query modules are for Python

2022-06-13 09:09 UTC, katarinasupe approved these changes

2022-06-13 09:54 UTC, brunos252 approved these changes

2022-06-13 11:38 UTC, merged