Initial implementation; Minor refactoring
memgraph/gqlalchemy pull request #164
Opened 2022-06-07 07:43 UTC by BorisTasevski

### Description

Please briefly explain the changes you made here.

### Pull request type

Please delete options that are not relevant.

- [ ] Bugfix
- [X] Feature
- [X] Code style update (formatting, renaming)
- [X] Refactoring with functional or API changes
- [ ] Refactoring without functional or API changes
- [ ] Build or packaging related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Related issues

[Have a way to wait for active connection](https://github.com/memgraph/gqlalchemy/issues/133)

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [memgraph/docs](https://github.com/memgraph/docs)

######################################

2022-06-07 08:03 UTC, katarinasupe requested changes

2022-06-07 15:36 UTC, katarinasupe submitted a review, later dismissed

2022-06-07 15:36 UTC, katarinasupe commented on gqlalchemy/exceptions.py
> +        super().__init__()
Is this line necessary?

2022-06-07 15:36 UTC, katarinasupe commented on gqlalchemy/instance_runner.py
> +    """Wait for a memgraph instance to become available.
Memgraph*

2022-06-07 15:36 UTC, katarinasupe commented on gqlalchemy/instance_runner.py
> +        memgraph: The instance of memgraph in to be waited to become available.
Memgraph*

2022-06-07 15:36 UTC, katarinasupe commented on gqlalchemy/instance_runner.py
> +      GQLAlchemyConnectionError: Raises an error when the memgraph instance isn't answering after the
Memgraph*

2022-06-08 07:16 UTC, katarinasupe commented on gqlalchemy/instance_runner.py
> +    """Wait for a memgraph instance to become available.
@BorisTasevski did you fix this?

2022-06-08 08:27 UTC, BorisTasevski commented on gqlalchemy/instance_runner.py
> +    """Wait for a memgraph instance to become available.
Oui, below as well

2022-06-14 11:52 UTC, g-despot approved these changes

2022-06-14 13:27 UTC, Josipmrden reviewed
Small changes needed

2022-06-14 13:52 UTC, katarinasupe approved these changes

2022-06-14 13:53 UTC, merged