Add transactions queries
memgraph/gqlalchemy pull request #310
Opened 2024-06-24 11:40 UTC by katarinasupe

### Description

I added get transactions and terminate transactions methods for easier transaction management.

### Pull request type

- [x] Feature

### Related issues

Closes #240 

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation TODO generate reference guide
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

######################################

### Reviewer checklist (the reviewer checks this part)
- [ ] Core feature implementation
- [ ] Tests
- [ ] Code documentation
- [ ] Documentation on [gqlalchemy/docs](https://github.com/memgraph/gqlalchemy/tree/main/docs)

######################################

2024-06-24 13:06 UTC, antepusic requested changes
I think this is all right once you apply the below suggestion:

2024-06-24 13:06 UTC, antepusic commented on gqlalchemy/vendors/memgraph.py
> +        print(terminated_transactions)
Remove the debug comments:
```suggestion
        terminated_transactions = []
        results = self.execute_and_fetch(query)

        for result in results:
            terminated_transactions.append(MemgraphTerminatedTransaction(result["transaction_id"], result["killed"]))
```

2024-06-24 13:07 UTC, antepusic commented
@katarinasupe Is this also milestone 1.6.0 like #309?

2024-06-24 13:13 UTC, katarinasupe commented
> @katarinasupe Is this also milestone 1.6.0 like #309?

Yes! Thank you, I updated it. I just need to deal with the tests first since I bumped up Memgraph in the workflow :D Then I'll incorporate your suggestions.

2024-06-25 05:52 UTC, as51340 reviewed
Nice work, few comments

2024-06-25 05:52 UTC, as51340 commented on tests/ogm/test_transactions.py
> +    assert len(result) == 1
please add test for terminate transactions also

2024-06-25 05:52 UTC, as51340 commented on gqlalchemy/vendors/memgraph.py
> +            transactions.append(transaction)
```suggestion
transactions_data = self.execute_and_fetch("SHOW TRANSACTIONS;")

# Define a helper function to create a MemgraphTransaction object from transaction data.
def create_transaction(transaction_data):
    return MemgraphTransaction(
        username=transaction_data["username"],
        transaction_id=transaction_data["transaction_id"],
        query=transaction_data["query"],
        metadata=transaction_data["metadata"],
    )

transactions = list(map(create_transaction, transactions_data))

```

2024-06-25 05:52 UTC, as51340 commented on gqlalchemy/vendors/memgraph.py
> +        print(terminated_transactions)
you can use map here in the same way

2024-07-05 06:11 UTC, as51340 approved these changes
Just one small comment, otherwise good, I will approve. Delete unnecessary variable initialization

2024-07-05 06:11 UTC, as51340 commented on gqlalchemy/vendors/memgraph.py
> +        terminated_transactions = []
delete this

2024-07-09 09:06 UTC, antepusic approved these changes
Seconding Andi’s comment

2024-07-09 12:31 UTC, merged