Add new Cypher clauses to the query builder
memgraph/gqlalchemy pull request #70
Opened 2022-01-12 16:34 UTC by g-despot

Add Cypher clauses to the query builder:

- [x] CALL
- [x] WITH
- [x] UNWIND
- [x] RETURN
- [x] YIELD
- [x] ORDER BY
- [x] LIMIT
- [x] CREATE
- [x] MERGE

2022-01-13 06:43 UTC, gitbuda commented
@g-despot when the code is done (decision about how exactly the object will be called), `README.md` also has to be updated 😄

2022-01-13 19:56 UTC, g-despot commented
@MasterMedo check out this PR when you get the chance so I know if I am going in the right direction with implementing all the missing Cypher queries in the query builder. Still missing: `DELETE`, `LOAD CSV`, `MERGE`, `REMOVE`, `SET` and `UNION`.
I am currently missing an error handling layer and a logic layer to check if the constructed query is following basic Cypher syntax rules.

2022-01-14 07:34 UTC, MasterMedo commented
I gotta admit, I greatly dislike the name `G`. I think it's better to be explicit. Class names should be self-explanatory. I'd much rather if we'd create a `DeclarativeBase` class and exposed it's starting properties as objects to be imported e.g.
```python
match = DeclarativeBase().match
merge = DeclarativeBase().merge
```
.
```python
from gqlalchemy import match, merge
```

Another idea is to just rename the `G` object to `QueryBuilder` or some other better name.

2022-01-14 07:40 UTC, MasterMedo requested changes

2022-01-14 07:40 UTC, MasterMedo commented on gqlalchemy/query_builder.py
> +            return f" WITH * "
when does this happen?

2022-01-14 07:40 UTC, MasterMedo commented on gqlalchemy/query_builder.py
> +class G:
Suggested names: `QueryBuilder`, `DeclarativeBase`, `QueryBase`

2022-01-18 06:44 UTC, gitbuda commented on gqlalchemy/query_builder.py
> +        f"{key} AS {value}" if value != "" and key != value else f"{key}" for (key, value) in alias_dict.items()
@g-despot great improvement!

2022-01-18 08:00 UTC, MasterMedo requested changes
Create and Merge need to be added.

2022-01-18 11:00 UTC, MasterMedo approved these changes

2022-01-18 11:40 UTC, merged